### ISSUE TITLE
Error in checkForRemoteErrors(val):

### ISSUE THREAD

**Issue by LeqiXu** [qlu-lab/X-Wing#1]
After summary statistics of BMI being restricted to hm3 SNPs with LDHub filtering procedure, LOGODetect will produce error as showed in the figure. And I'd really appreciate it if you have any suggestions for that.
![LOGODetect_error](https://github.com/qlu-lab/X-Wing/assets/49301831/a8aa2024-ffa9-47b7-9b44-48bd6638f50e)

**Comment by ghm17** [comment]
We have just updated the script `LOGODetect.R`. Please try the updated version and let us know if you still have errors.

**Comment by xinyu-c9** [comment]
I still have the same error when I try the latest version of LOGODetect.R.
![image](https://github.com/qlu-lab/X-Wing/assets/116093647/5e7af58b-b54b-4b3c-b69f-98854b77c4c4)

![image](https://github.com/qlu-lab/X-Wing/assets/116093647/170399e4-e836-4b10-8b31-9b19083d0977)

I use Liftover tools to transform the genome build of reference from hg19 to hg38, coding the id as chr:pos:a1:a2, and remove duplicate id from the plink file and ldscore file. 

After this, I run the script use:

`
Rscript ../software/X_Wing/LOGODetect.R --sumstats ./test_CAD_EAS,./test_CAD_EUR --n_gwas 184305,178726 --ref_dir /software/reference/LOGODetect_1kg_ref --pop EUR,EAS --block_partition /LD_reference/ldblock_hg38 --gc_snp /LD_reference/snpid_hg38 --out_dir . --n_cores 8 --target_pop EUR --n_topregion 1000
`

If you need further information, I'd like to provide my reference file and GWAS file to you.

Thanks a lot in advance if you could help me to solve this.

Best!

**Comment by ghm17** [comment]
I think a more convenient way is to transform the genome build of input GWAS summary statistics from hg38 to hg19, which will be less likely to cause inconsitency running the tool. If the error still occurs, maybe you can share the input GWAS files with us to take a deeper look into what's going on.
